### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by SilentVisionDev** [byteseb/Grafobook#2]
Could you please add a Widget for GraphoBook. Something similar to the Samsung Notes Widget which you can place on your home screen to easily add notes without opening the app. Thanks in advance.

**Comment by byteseb** [comment]
Yes! Currently working on the feature for 1.2 update. You could expect it to be released before the month ends :)
![Screenshot_1625981219](https://user-images.githubusercontent.com/85042318/125183769-bfb17700-e1de-11eb-974b-3399f1e50ce2.png)

**Comment by SilentVisionDev** [comment]
Love you ❤️ thanks!
